# Modifier les paramètres par défaut d'affichage de dataframe sur Jupyter Notebook

In [1]:
import pandas as pd
import numpy as np

# Nombre maximal de lignes

In [2]:
# Nombre de lignes par défaut
print(pd.get_option('display.max_rows'))
print(pd.options.display.max_rows)

60
60

In [3]:
df = pd.DataFrame(np.random.randn(100, 3))
df

           0         1         2
0  -0.260609 -0.803806 -0.603028
1  -1.028422 -0.498297  0.381929
2  -0.301133  0.556596  1.010230
3  -1.560411 -2.778900  1.842691
4   0.213558  0.577209 -0.257845
..       ...       ...       ...
95  0.750590  1.465812 -0.433719
96 -0.247911 -0.320803 -2.729259
97 -1.667073  0.258905  0.568930
98 -0.060951  0.252284 -0.622904
99  0.169425 -0.864758  0.504668

[100 rows x 3 columns]

In [4]:
# modifier la valeur
pd.set_option('display.max_rows', 400)

In [5]:
df

           0         1         2
0  -0.260609 -0.803806 -0.603028
1  -1.028422 -0.498297  0.381929
2  -0.301133  0.556596  1.010230
3  -1.560411 -2.778900  1.842691
4   0.213558  0.577209 -0.257845
5   0.895229  1.754104 -0.157839
6  -1.055048 -0.686827  1.084154
7  -0.535531 -0.692134  1.581402
8  -0.282851 -0.044797 -0.766589
9  -0.834899  0.927937  1.875337
10  1.030401  0.849718  0.231520
11 -0.599950  0.127343  1.740036
12 -0.197111  0.260992 -1.064395
13  2.176136  0.713443 -1.879437
14 -0.373405  0.936207  0.819469
15 -0.710570 -0.697007 -1.749535
16  1.493241 -2.956647  0.215165
17  0.088503 -2.248319  0.909540
18 -0.120870  0.799716 -0.829997
19  0.245020  1.454625  0.362598
20  0.070283  0.168491  0.661527
21 -0.887480 -0.287619  0.273814
22 -1.093804  0.469080  0.767406
23  0.834200 -1.141300 -0.329864
24  0.574448 -0.286796  0.487067
25  0.026308 -0.002051 -0.259964
26 -0.776608  2.332154 -0.420087
27  0.650430  0.363678  0.787157
28  0.923656  0.385540  0.259775
29  1.885016  0.113052  0.908730
30  0.310199  1.256546 -0.527783
31 -1.619400  0.958681 -1.264582
32  0.926158  2.200326  0.954409
33  1.867663 -0.053431 -1.324142
34  0.804626  0.166884  1.522985
35  0.252419  1.170770 -0.713063
36 -0.249378  2.710329 -3.517490
37 -0.202517  0.122726 -0.320270
38  0.515459  0.933776 -0.496460
39  0.962451 -1.132618 -0.559968
40 -1.798049  0.569988  0.099014
41  0.040201  0.969177 -0.306467
42  1.430717 -0.201367  1.121007
43  0.181241  0.027925  1.308327
44 -0.188227  0.172580 -1.831460
45 -0.398209 -2.303236  0.869157
46  0.121399 -0.005825  0.531942
47  1.084841 -0.746515 -0.376785
48 -0.929865  0.888750 -0.088116
49 -0.177711  1.494720  0.427014
50  0.120978  0.316750 -0.620306
51  1.205863 -0.280997  1.388750
52 -0.557502  0.729902 -1.165992
53  0.297003 -1.962812  0.466615
54 -0.352072  0.187100 -0.222772
55  1.458295  0.688374 -1.209787
56 -0.515154  1.013544  1.146108
57 -0.175333 -0.400713  0.918170
58 -0.695670  0.687567  0.132327
59  0.506191 -0.628037 -2.069605
60  1.842439  0.431160  0.679559
61  0.293710  0.649841  0.229435
62  0.430696  0.844335 -0.112697
63 -0.539943 -0.820332  0.146416
64  0.273868  1.351867 -1.224496
65  0.022159  0.693929 -0.306381
66 -2.464665  0.385318  1.036547
67  0.399022  0.988546 -0.850575
68 -1.671901  0.580234  0.349473
69  1.197637  0.414055  0.245227
70  0.493280 -0.441458  0.190726
71 -0.304244 -0.234161  0.453363
72  1.285614  0.094081 -2.616007
73 -0.743992  0.162945 -1.643584
74 -0.170886  0.286889  0.421705
75 -0.000793 -1.036392 -1.803562
76 -0.915038  1.139330  1.441751
77 -0.104514  0.614711  0.707692
78  1.443912 -0.707373 -0.729075
79 -0.240339  0.305314 -0.491972
80 -0.671062 -0.626933 -1.187891
81  0.981704  0.681701 -1.215282
82  0.656323 -0.254578  1.460235
83  0.993303  0.636544 -0.383371
84  0.057248 -0.567507 -0.299868
85  1.889432 -1.669561 -2.176648
86  1.244445  1.459233  0.283971
87 -0.734198 -2.145357 -0.556900
88 -0.697847 -0.880971  2.587982
89  1.773244  0.199846 -0.775173
90 -0.919171 -0.523178  1.816242
91  0.207628  0.827804 -0.819005
92  0.550374 -0.917757 -0.341951
93 -0.950899  0.688863  1.492224
94 -0.903364 -0.256913  0.815077
95  0.750590  1.465812 -0.433719
96 -0.247911 -0.320803 -2.729259
97 -1.667073  0.258905  0.568930
98 -0.060951  0.252284 -0.622904
99  0.169425 -0.864758  0.504668

# Nombre maximal de colonnes

In [6]:
# Nombre de colonnes par défaut
print(pd.get_option('display.max_columns'))
print(pd.options.display.max_columns)

20
20

In [7]:
df = pd.DataFrame(np.random.randn(10, 30))
df

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,0.400361,0.585132,0.250104,1.213961,-1.027559,2.085343,-1.208389,-0.993947,0.107087,0.790493,...,-0.251541,-0.977673,-2.233531,-0.067890,1.310481,-1.121234,-0.060577,0.457653,0.556240,0.538154
1,-0.135506,-0.220047,0.612027,0.255971,-1.789491,1.305809,1.763646,0.912519,1.532108,0.361354,...,1.359284,-0.428685,0.792190,-0.562388,-0.254271,-0.601778,-0.557409,1.661816,0.508860,-0.392661
2,0.034405,0.104597,-0.512198,0.044753,-0.397324,0.181435,0.453088,-0.290678,0.659403,-0.735349,...,-0.376518,-0.316714,-0.810829,1.578297,0.840599,0.349363,0.419512,0.669502,-0.639173,1.512637
3,1.182060,-1.349680,0.680909,-1.208585,0.664401,2.291694,1.065145,0.033765,-0.256661,0.372630,...,1.139053,0.824603,-0.542743,-1.973111,0.227889,-1.340851,0.175065,0.614575,-2.133745,0.058723
4,-0.117164,0.009462,-0.005137,-0.750405,0.532995,0.951255,-1.261881,0.939965,-0.370199,-0.200469,...,0.759504,-1.293004,1.079752,1.985033,0.202025,-0.496572,0.872519,0.268627,0.032059,0.141569
5,1.512378,-1.144140,0.693282,-0.234550,0.425241,-0.025699,-1.546971,-1.505464,1.655932,-0.226770,...,-0.488804,0.714107,1.056754,0.304286,2.405539,0.003965,-0.161212,0.251198,1.029053,0.390935
6,0.483531,-0.629969,1.658028,1.343780,-0.707444,-1.345083,-2.415280,-1.194470,1.890827,0.467782,...,-0.344614,-0.967473,0.689939,0.073036,1.150756,0.237617,0.905834,1.200760,-0.060204,0.957157
7,1.282433,0.586549,1.474621,-0.832650,-0.760322,1.512786,0.196857,0.347275,-1.212188,-0.757318,...,-0.880702,-0.595207,0.196423,-1.485596,-0.993220,0.816735,0.361207,0.400842,1.431149,0.466471
8,-0.418331,0.235117,1.680639,-0.472576,-0.304727,-1.226673,-0.949690,1.444327,-0.315203,0.017379,...,-0.863844,1.036185,-0.192866,-0.816240,-0.033593,-0.175335,-2.226616,0.002121,0.899535,0.752820
9,-1.381357,1.083877,-1.078173,-0.249777,-0.343521,0.342093,1.143402,0.611279,1.174546,-1.596933,...,-0.024685,1.021019,0.541903,-0.883102,0.020104,-0.583506,0.893434,-1.090166,-0.219301,1.032286

In [8]:
# modification du nombre maximal de colonnes à afficher
pd.options.display.max_columns = 50

In [9]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29
0,0.400361,0.585132,0.250104,1.213961,-1.027559,2.085343,-1.208389,-0.993947,0.107087,0.790493,1.084685,-0.570760,1.634462,-1.976101,-0.503533,1.569334,0.071276,1.578624,1.112385,1.498724,-0.251541,-0.977673,-2.233531,-0.067890,1.310481,-1.121234,-0.060577,0.457653,0.556240,0.538154
1,-0.135506,-0.220047,0.612027,0.255971,-1.789491,1.305809,1.763646,0.912519,1.532108,0.361354,-0.881401,-1.451718,-1.264831,-0.826264,1.090518,-1.664139,-0.929201,-0.544720,-0.823734,0.792878,1.359284,-0.428685,0.792190,-0.562388,-0.254271,-0.601778,-0.557409,1.661816,0.508860,-0.392661
2,0.034405,0.104597,-0.512198,0.044753,-0.397324,0.181435,0.453088,-0.290678,0.659403,-0.735349,1.243367,0.656784,-1.076702,0.679030,-0.470942,2.115546,-0.141076,-0.907559,1.217343,-1.107916,-0.376518,-0.316714,-0.810829,1.578297,0.840599,0.349363,0.419512,0.669502,-0.639173,1.512637
3,1.182060,-1.349680,0.680909,-1.208585,0.664401,2.291694,1.065145,0.033765,-0.256661,0.372630,-0.533960,0.893098,-0.476786,-0.006619,-0.538977,0.039665,-0.694152,2.384403,-1.433871,2.259184,1.139053,0.824603,-0.542743,-1.973111,0.227889,-1.340851,0.175065,0.614575,-2.133745,0.058723
4,-0.117164,0.009462,-0.005137,-0.750405,0.532995,0.951255,-1.261881,0.939965,-0.370199,-0.200469,-0.692297,-0.924916,-1.046741,-0.830954,0.662059,0.207550,1.673438,2.042487,0.524710,-1.024348,0.759504,-1.293004,1.079752,1.985033,0.202025,-0.496572,0.872519,0.268627,0.032059,0.141569
5,1.512378,-1.144140,0.693282,-0.234550,0.425241,-0.025699,-1.546971,-1.505464,1.655932,-0.226770,-0.598967,-0.593741,0.839494,1.009285,1.906576,-0.661916,-0.603650,-0.279517,-0.648937,-0.885873,-0.488804,0.714107,1.056754,0.304286,2.405539,0.003965,-0.161212,0.251198,1.029053,0.390935
6,0.483531,-0.629969,1.658028,1.343780,-0.707444,-1.345083,-2.415280,-1.194470,1.890827,0.467782,0.519394,-1.494251,-0.750058,-0.641108,0.594476,-1.072286,-1.129074,-1.386067,-0.803043,0.172918,-0.344614,-0.967473,0.689939,0.073036,1.150756,0.237617,0.905834,1.200760,-0.060204,0.957157
7,1.282433,0.586549,1.474621,-0.832650,-0.760322,1.512786,0.196857,0.347275,-1.212188,-0.757318,0.068781,-2.127708,0.357481,0.106713,-1.116996,0.175537,-0.071350,-0.253288,1.406300,0.722094,-0.880702,-0.595207,0.196423,-1.485596,-0.993220,0.816735,0.361207,0.400842,1.431149,0.466471
8,-0.418331,0.235117,1.680639,-0.472576,-0.304727,-1.226673,-0.949690,1.444327,-0.315203,0.017379,-0.631741,-0.306571,-0.531864,-1.071053,-0.193689,-1.740209,-0.206505,1.668780,0.239669,-1.666018,-0.863844,1.036185,-0.192866,-0.816240,-0.033593,-0.175335,-2.226616,0.002121,0.899535,0.752820
9,-1.381357,1.083877,-1.078173,-0.249777,-0.343521,0.342093,1.143402,0.611279,1.174546,-1.596933,-0.561905,-0.022023,-1.094115,0.568039,-1.837410,-1.502353,0.277820,-0.038219,-0.419802,-0.133992,-0.024685,1.021019,0.541903,-0.883102,0.020104,-0.583506,0.893434,-1.090166,-0.219301,1.032286

# Largeur de colonnes

In [10]:
# Largeur de colonnes
print(pd.get_option('max_colwidth'))
print(pd.options.display.max_colwidth)

50
50

In [11]:
df = pd.DataFrame({"text": ["pandas jupyter settings "*2, "print data into notebook jupyter"*3],
                   "range": [1, 2]
                  })
df

                                                text  range
0   pandas jupyter settings pandas jupyter settings       1
1  print data into notebook jupyterprint data int...      2

In [12]:
pd.options.display.max_colwidth = 100

In [13]:
df

,text,range
0,pandas jupyter settings pandas jupyter settings,1
1,print data into notebook jupyterprint data into notebook jupyterprint data into notebook jupyter,2

# Nombre de colonnes à afficher avec la méthode `info()`

In [14]:
# Nombre maximal de colonnes par défaut 
pd.options.display.max_info_columns

100

In [15]:
# changeons la valeur
pd.options.display.max_info_columns = 10

In [16]:
df = pd.DataFrame(np.random.randn(10, 30))
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Columns: 30 entries, 0 to 29
dtypes: float64(30)
memory usage: 2.5 KB

In [17]:
# changeons la valeur
pd.options.display.max_info_columns = 10
df = pd.DataFrame(np.random.randn(10, 9))
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       10 non-null     float64
 1   1       10 non-null     float64
 2   2       10 non-null     float64
 3   3       10 non-null     float64
 4   4       10 non-null     float64
 5   5       10 non-null     float64
 6   6       10 non-null     float64
 7   7       10 non-null     float64
 8   8       10 non-null     float64
dtypes: float64(9)
memory usage: 848.0 bytes

# Nombre de décimales

In [18]:
# nombre de chiffres à afficher dans la partie décimale
pd.options.display.precision

6

In [19]:
df = pd.DataFrame(10+np.random.randn(10, 3))
df

           0          1          2
0  10.358930   9.401499   9.469960
1  10.212324   8.158972   9.201826
2  10.507569   8.894944   9.767474
3   9.471936  12.368493   8.541015
4   8.112053  10.544189  10.163919
5   8.749560   9.773081  11.362258
6  10.449224  11.691026   9.539987
7  10.211768   9.698739  10.924387
8   9.611227   9.331555  10.627375
9   7.932814   8.570697   9.288321

In [20]:
# modifions à deux chiffres dans la partie décimale
pd.options.display.precision=2

# affichons à nouveau le df
df

       0      1      2
0  10.36   9.40   9.47
1  10.21   8.16   9.20
2  10.51   8.89   9.77
3   9.47  12.37   8.54
4   8.11  10.54  10.16
5   8.75   9.77  11.36
6  10.45  11.69   9.54
7  10.21   9.70  10.92
8   9.61   9.33  10.63
9   7.93   8.57   9.29

# Changer la largeur des céllules

In [22]:
# Settings pour l'affichage du notebook
from IPython.display import display, HTML
display(HTML("<style>.container {width:95% !important; }</style>"))

# Modifier la taille des caractères

In [27]:
# Settings pour l'affichage du notebook
from IPython.display import display, HTML
display(HTML("<style type='text/css'>.CodeMirror{font-family: consolas; font-size: 14.4px;</style>"))