# Sélectionner des données à partir des types

In [2]:
# packages
import pandas as pd

## read data

In [3]:
# data
orders_data = pd.read_csv("/datasets/google-drive/Datasets/orders.csv")
orders_data["order_date"] = pd.to_datetime(orders_data["order_date"], format="%Y/%m/%d")

print(orders_data.head())

  order_date  pages_visited         order_id customer_id  tshirt_category  \
0 2016-09-04              9  HTS-038040-0002      038040  White T-Shirt M
1 2014-11-14             11  HTS-801797-0001      801797  White T-Shirt M
2 2017-02-26             10  HTS-vft1eu-0003      vft1eu  White T-Shirt F
3 2013-12-01             10  HTS-914324-0001      914324      Wh Tshirt F
4 2015-10-22             12  HTS-88ua9r-0001      88ua9r  White T-Shirt M

   tshirt_price  tshirt_quantity
0          20.0                1
1          20.0                1
2          18.0                3
3          18.0                1
4          20.0                1

In [4]:
# get columns data types
orders_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26552 entries, 0 to 26551
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_date       26552 non-null  datetime64[ns]
 1   pages_visited    26552 non-null  int64
 2   order_id         26552 non-null  object
 3   customer_id      26552 non-null  object
 4   tshirt_category  26552 non-null  object
 5   tshirt_price     26552 non-null  float64
 6   tshirt_quantity  26552 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 1.4+ MB

## Select some columns types

In [5]:
# select columns with int and float data types
print(orders_data.select_dtypes(include=["int", "float"]))

       pages_visited  tshirt_price  tshirt_quantity
0                  9          20.0                1
1                 11          20.0                1
2                 10          18.0                3
3                 10          18.0                1
4                 12          20.0                1
...              ...           ...              ...
26547             13          20.0                1
26548              4          20.0                1
26549              6          20.0                1
26550             11          23.0                5
26551              9          19.0                3

[26552 rows x 3 columns]

## Exclude some columns types

In [6]:
# exclude columns with int data type
print(orders_data.select_dtypes(exclude=["int"]))

      order_date         order_id customer_id  tshirt_category  tshirt_price
0     2016-09-04  HTS-038040-0002      038040  White T-Shirt M          20.0
1     2014-11-14  HTS-801797-0001      801797  White T-Shirt M          20.0
2     2017-02-26  HTS-vft1eu-0003      vft1eu  White T-Shirt F          18.0
3     2013-12-01  HTS-914324-0001      914324      Wh Tshirt F          18.0
4     2015-10-22  HTS-88ua9r-0001      88ua9r  White T-Shirt M          20.0
...          ...              ...         ...              ...           ...
26547 2016-11-19  HTS-n641x4-0001      n641x4  White T-Shirt M          20.0
26548 2016-08-02  HTS-q0nm12-0001      q0nm12  White T-Shirt M          20.0
26549 2017-03-09  HTS-sby0iz-0001      sby0iz  White T-Shirt M          20.0
26550 2016-10-04  HTS-uz70x4-0001      uz70x4           Hoodie          23.0
26551 2016-12-16  HTS-xnbc22-0001      xnbc22  Black T-Shirt M          19.0

[26552 rows x 5 columns]